# Generated by Django 4.1.7 on 2023-03-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='username',
            new_name='name',
        ),
    ]
