# Generated by Django 4.1.7 on 2023-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0002_rename_username_userdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='mobile',
            field=models.CharField(default='9158423684', max_length=50),
        ),
    ]
