# Generated by Django 4.1.7 on 2023-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0003_userdetail_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='address',
            field=models.CharField(default='pimple gurav', max_length=50),
        ),
    ]
