# Generated by Django 4.1.7 on 2023-04-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0004_userdetail_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='address',
        ),
    ]
