# Generated by Django 4.1.7 on 2023-04-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0005_remove_userdetail_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetail',
        ),
    ]
