# Generated by Django 4.1.7 on 2023-04-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('palour', '0006_delete_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('mobile', models.CharField(default='9158423684', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('services', models.CharField(choices=[('FA', 'Facial'), ('HR', 'Hair treatement'), ('WA', 'waxing'), ('MK', 'Makeup')], max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
