# Generated by Django 4.1.7 on 2023-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlour',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
