# Generated by Django 4.1.7 on 2023-04-13 07:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0008_alter_parlour_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('regno', models.CharField(max_length=20, unique=True)),
                ('parlourname', models.CharField(max_length=20)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='9195969897', max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('confirmpassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Parlour',
        ),
    ]
