# Generated by Django 4.1.7 on 2023-04-13 07:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0009_clientdetail_userdetail_delete_parlour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='parlourname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
