# Generated by Django 4.1.7 on 2023-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0010_alter_clientdetail_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
