# Generated by Django 4.1.7 on 2023-04-16 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0011_alter_clientdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='parlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parlour_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('parlour_image', models.ImageField(upload_to='parlour')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.clientdetail')),
            ],
        ),
    ]
