# Generated by Django 4.1.7 on 2023-04-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0013_remove_parlour_username_alter_parlour_parlour_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Pedicure', 'Pedicure'), ('facial', 'facial'), ('Manicure', 'Manicure'), ('Hair Straiting', 'Hair Straiting'), ('makeup', 'makeup'), ('Threading', 'Threading'), ('Hair Spa', 'Hair Spa')], max_length=20)),
                ('description', models.TextField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.parlour')),
            ],
        ),
    ]
