# Generated by Django 4.1.7 on 2023-04-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0014_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='services',
        ),
    ]
