# Generated by Django 4.1.7 on 2023-04-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0015_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('facial', 'facial'), ('Pedicure', 'Pedicure'), ('Threading', 'Threading'), ('Hair Straiting', 'Hair Straiting'), ('Hair Spa', 'Hair Spa'), ('makeup', 'makeup'), ('Manicure', 'Manicure')], max_length=20)),
                ('description', models.TextField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services_image', models.ImageField(upload_to='service')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.parlour')),
            ],
        ),
    ]
