# Generated by Django 4.1.7 on 2023-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0016_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('facial', 'facial'), ('makeup', 'makeup'), ('Threading', 'Threading'), ('Manicure', 'Manicure'), ('Pedicure', 'Pedicure'), ('Hair Straiting', 'Hair Straiting'), ('Hair Spa', 'Hair Spa')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
