# Generated by Django 4.1.7 on 2023-04-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0017_servicemaster_delete_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('makeup', 'makeup'), ('Hair Spa', 'Hair Spa'), ('facial', 'facial'), ('Manicure', 'Manicure'), ('Hair Straiting', 'Hair Straiting'), ('Threading', 'Threading'), ('Pedicure', 'Pedicure')], max_length=20),
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('services_image', models.ImageField(upload_to='service')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.parlour')),
                ('servicename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.servicemaster')),
            ],
        ),
    ]
