# Generated by Django 4.1.7 on 2023-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0018_alter_servicemaster_service_name_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Manicure', 'Manicure'), ('makeup', 'makeup'), ('facial', 'facial'), ('Hair Straiting', 'Hair Straiting'), ('Pedicure', 'Pedicure'), ('Threading', 'Threading'), ('Hair Spa', 'Hair Spa')], max_length=20),
        ),
    ]
