# Generated by Django 4.1.7 on 2023-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0019_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='services_image',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Threading', 'Threading'), ('makeup', 'makeup'), ('Hair Spa', 'Hair Spa'), ('Manicure', 'Manicure'), ('Hair Straiting', 'Hair Straiting'), ('Pedicure', 'Pedicure'), ('facial', 'facial')], max_length=20),
        ),
    ]
