# Generated by Django 4.1.7 on 2023-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0020_remove_services_services_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Pedicure', 'Pedicure'), ('Hair Straiting', 'Hair Straiting'), ('makeup', 'makeup'), ('facial', 'facial'), ('Manicure', 'Manicure'), ('Hair Spa', 'Hair Spa'), ('Threading', 'Threading')], max_length=20),
        ),
    ]
