# Generated by Django 4.1.7 on 2023-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0021_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('facial', 'facial'), ('Manicure', 'Manicure'), ('Hair Spa', 'Hair Spa'), ('Pedicure', 'Pedicure'), ('Threading', 'Threading'), ('makeup', 'makeup'), ('Hair Straiting', 'Hair Straiting')], max_length=20),
        ),
    ]
