# Generated by Django 4.1.7 on 2023-04-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0022_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Threading', 'Threading'), ('Hair Straiting', 'Hair Straiting'), ('Pedicure', 'Pedicure'), ('Manicure', 'Manicure'), ('Hair Spa', 'Hair Spa'), ('facial', 'facial'), ('makeup', 'makeup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.clientdetail'),
        ),
    ]
