# Generated by Django 4.1.7 on 2023-04-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0024_rename_pname_services_parlourname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('facial', 'facial'), ('Manicure', 'Manicure'), ('Threading', 'Threading'), ('Pedicure', 'Pedicure'), ('makeup', 'makeup'), ('Hair Straiting', 'Hair Straiting'), ('Hair Spa', 'Hair Spa')], max_length=20),
        ),
    ]
