# Generated by Django 4.1.7 on 2023-04-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0025_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Pedicure', 'Pedicure'), ('makeup', 'makeup'), ('Manicure', 'Manicure'), ('facial', 'facial'), ('Hair Spa', 'Hair Spa'), ('Hair Straiting', 'Hair Straiting'), ('Threading', 'Threading')], max_length=20),
        ),
    ]
