# Generated by Django 4.1.7 on 2023-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0026_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('facial', 'facial'), ('makeup', 'makeup'), ('Hair Spa', 'Hair Spa'), ('Threading', 'Threading'), ('Pedicure', 'Pedicure'), ('Manicure', 'Manicure'), ('Hair Straiting', 'Hair Straiting')], max_length=20),
        ),
    ]
