# Generated by Django 4.1.7 on 2023-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0027_rename_services_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='parlourname',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Threading', 'Threading'), ('Manicure', 'Manicure'), ('facial', 'facial'), ('Hair Straiting', 'Hair Straiting'), ('makeup', 'makeup'), ('Hair Spa', 'Hair Spa'), ('Pedicure', 'Pedicure')], max_length=20),
        ),
    ]
