# Generated by Django 4.1.7 on 2023-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0028_rename_parlourname_service_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair Spa', 'Hair Spa'), ('Manicure', 'Manicure'), ('Hair Straiting', 'Hair Straiting'), ('Pedicure', 'Pedicure'), ('facial', 'facial'), ('makeup', 'makeup'), ('Threading', 'Threading')], max_length=20),
        ),
    ]
