# Generated by Django 4.1.7 on 2023-04-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0030_rename_username_service_parlourname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='parlourname',
            new_name='clientdetail',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair Straiting', 'Hair Straiting'), ('makeup', 'makeup'), ('Pedicure', 'Pedicure'), ('facial', 'facial'), ('Manicure', 'Manicure'), ('Threading', 'Threading'), ('Hair Spa', 'Hair Spa')], max_length=20),
        ),
    ]
