# Generated by Django 4.1.7 on 2023-04-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0031_rename_parlourname_service_clientdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='clientdetail',
            new_name='parlourname',
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Manicure', 'Manicure'), ('facial', 'facial'), ('Threading', 'Threading'), ('makeup', 'makeup'), ('Hair Straiting', 'Hair Straiting'), ('Hair Spa', 'Hair Spa'), ('Pedicure', 'Pedicure')], max_length=20),
        ),
    ]
