# Generated by Django 4.1.7 on 2023-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0032_rename_clientdetail_service_parlourname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair smoothening', 'Hair smoothening'), ('Waxing', 'Waxing'), ('Hair Spa', 'Hair Spa'), ('Makeup', 'Makeup'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Nail art', 'Nail art'), ('Hair straightening', 'Hair straightening'), ('Facial', 'Facial'), ('Threading', 'Threading'), ('Manicure', 'Manicure'), ('Haircuts', 'Haircuts'), ('Bleach', 'Bleach'), ('Pedicure', 'Pedicure'), ('Hairstyling', 'Hairstyling')], max_length=50),
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
