# Generated by Django 4.1.7 on 2023-04-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0033_alter_servicemaster_service_name_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair straightening', 'Hair straightening'), ('Hair smoothening', 'Hair smoothening'), ('Waxing', 'Waxing'), ('Pedicure', 'Pedicure'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Haircuts', 'Haircuts'), ('Hairstyling', 'Hairstyling'), ('Bleach', 'Bleach'), ('Makeup', 'Makeup'), ('Nail art', 'Nail art'), ('Facial', 'Facial'), ('Threading', 'Threading'), ('Hair Spa', 'Hair Spa'), ('Manicure', 'Manicure')], max_length=50),
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='service')),
                ('description', models.TextField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parlourname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.clientdetail')),
                ('servicename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.servicemaster')),
            ],
        ),
    ]
