# Generated by Django 4.1.7 on 2023-04-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0034_alter_servicemaster_service_name_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='servicemaster',
        ),
    ]
