# Generated by Django 4.1.7 on 2023-04-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0035_delete_service_delete_servicemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Waxing', 'Waxing'), ('Makeup', 'Makeup'), ('Hair straightening', 'Hair straightening'), ('Haircuts', 'Haircuts'), ('Hair smoothening', 'Hair smoothening'), ('Pedicure', 'Pedicure'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Bleach', 'Bleach'), ('Manicure', 'Manicure'), ('Nail art', 'Nail art'), ('Facial', 'Facial'), ('Hairstyling', 'Hairstyling'), ('Hair Spa', 'Hair Spa'), ('Threading', 'Threading')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='service')),
                ('description', models.TextField()),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parlourname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.clientdetail')),
                ('servicename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.servicemaster')),
            ],
        ),
    ]
