# Generated by Django 4.1.7 on 2023-04-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0036_servicemaster_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Threading', 'Threading'), ('Hair straightening', 'Hair straightening'), ('Facial', 'Facial'), ('Nail art', 'Nail art'), ('Manicure', 'Manicure'), ('Waxing', 'Waxing'), ('Hair smoothening', 'Hair smoothening'), ('Hair Spa', 'Hair Spa'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Hairstyling', 'Hairstyling'), ('Makeup', 'Makeup'), ('Haircuts', 'Haircuts'), ('Pedicure', 'Pedicure'), ('Bleach', 'Bleach')], max_length=50),
        ),
    ]
