# Generated by Django 4.1.7 on 2023-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0037_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair Spa', 'Hair Spa'), ('Hairstyling', 'Hairstyling'), ('Waxing', 'Waxing'), ('Hair smoothening', 'Hair smoothening'), ('Threading', 'Threading'), ('Makeup', 'Makeup'), ('Bleach', 'Bleach'), ('Manicure', 'Manicure'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Haircuts', 'Haircuts'), ('Nail art', 'Nail art'), ('Hair straightening', 'Hair straightening'), ('Pedicure', 'Pedicure'), ('Facial', 'Facial')], max_length=50, unique=True),
        ),
    ]
