# Generated by Django 4.1.7 on 2023-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0039_alter_clientdetail_regno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Pedicure', 'Pedicure'), ('Hair straightening', 'Hair straightening'), ('Threading', 'Threading'), ('Manicure', 'Manicure'), ('Makeup', 'Makeup'), ('Bleach', 'Bleach'), ('Hairstyling', 'Hairstyling'), ('Waxing', 'Waxing'), ('Hair smoothening', 'Hair smoothening'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Hair Spa', 'Hair Spa'), ('Nail art', 'Nail art'), ('Facial', 'Facial'), ('Haircuts', 'Haircuts')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
