# Generated by Django 4.1.7 on 2023-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0040_alter_servicemaster_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='parlourname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Makeup', 'Makeup'), ('Hair smoothening', 'Hair smoothening'), ('Threading', 'Threading'), ('Waxing', 'Waxing'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Facial', 'Facial'), ('Hair Spa', 'Hair Spa'), ('Nail art', 'Nail art'), ('Haircuts', 'Haircuts'), ('Pedicure', 'Pedicure'), ('Bleach', 'Bleach'), ('Hairstyling', 'Hairstyling'), ('Hair straightening', 'Hair straightening'), ('Manicure', 'Manicure')], max_length=50, unique=True),
        ),
    ]
