# Generated by Django 4.1.7 on 2023-04-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0041_alter_clientdetail_parlourname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='charges',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='discounted_charges',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair smoothening', 'Hair smoothening'), ('Hair straightening', 'Hair straightening'), ('Nail art', 'Nail art'), ('Manicure', 'Manicure'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Pedicure', 'Pedicure'), ('Threading', 'Threading'), ('Makeup', 'Makeup'), ('Hair Spa', 'Hair Spa'), ('Hairstyling', 'Hairstyling'), ('Haircuts', 'Haircuts'), ('Bleach', 'Bleach'), ('Waxing', 'Waxing'), ('Facial', 'Facial')], max_length=50, unique=True),
        ),
    ]
