# Generated by Django 4.1.7 on 2023-05-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0042_alter_service_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Waxing', 'Waxing'), ('Haircuts', 'Haircuts'), ('Hair Spa', 'Hair Spa'), ('Hair smoothening', 'Hair smoothening'), ('Hairstyling', 'Hairstyling'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Manicure', 'Manicure'), ('Threading', 'Threading'), ('Nail art', 'Nail art'), ('Bleach', 'Bleach'), ('Hair straightening', 'Hair straightening'), ('Makeup', 'Makeup'), ('Pedicure', 'Pedicure'), ('Facial', 'Facial')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.userdetail')),
            ],
        ),
    ]
