# Generated by Django 4.1.7 on 2023-05-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0043_alter_servicemaster_service_name_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.servicemaster'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Bleach', 'Bleach'), ('Hairstyling', 'Hairstyling'), ('Hair straightening', 'Hair straightening'), ('Haircuts', 'Haircuts'), ('Hair Spa', 'Hair Spa'), ('Facial', 'Facial'), ('Waxing', 'Waxing'), ('Hair smoothening', 'Hair smoothening'), ('Nail art', 'Nail art'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Pedicure', 'Pedicure'), ('Makeup', 'Makeup'), ('Manicure', 'Manicure'), ('Threading', 'Threading')], max_length=50, unique=True),
        ),
    ]
