# Generated by Django 4.1.7 on 2023-05-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0044_alter_cart_service_alter_servicemaster_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.service'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair straightening', 'Hair straightening'), ('Haircuts', 'Haircuts'), ('Threading', 'Threading'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Manicure', 'Manicure'), ('Facial', 'Facial'), ('Makeup', 'Makeup'), ('Nail art', 'Nail art'), ('Hair smoothening', 'Hair smoothening'), ('Pedicure', 'Pedicure'), ('Waxing', 'Waxing'), ('Hair Spa', 'Hair Spa'), ('Hairstyling', 'Hairstyling'), ('Bleach', 'Bleach')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('Time_slot', models.CharField(choices=[('21:00', '21:00'), ('13:00', '13:00'), ('18:00', '18:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('11:00', '11:00'), ('20:00', '20:00'), ('19:00', '19:00')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('parlourname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.clientdetail')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.userdetail')),
            ],
        ),
    ]
