# Generated by Django 4.1.7 on 2023-05-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0045_alter_cart_service_alter_servicemaster_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Time_slot',
            field=models.CharField(choices=[('18:00-19:00', '18:00-19:00'), ('12:00-13:00', '12:00-13:00'), ('11:00-12:00', '11:00-12:00'), ('19:00-20:00', '19:00-20:00'), ('13:00-14:00', '13:00-14:00'), ('10:00-11:00', '10:00-11:00'), ('21:00-22:00', '21:00-22:00'), ('20:00-21:00', '20:00-21:00')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Nail art', 'Nail art'), ('Waxing', 'Waxing'), ('Haircuts', 'Haircuts'), ('Manicure', 'Manicure'), ('Hairstyling', 'Hairstyling'), ('Hair smoothening', 'Hair smoothening'), ('Pedicure', 'Pedicure'), ('Bleach', 'Bleach'), ('Threading', 'Threading'), ('Hair straightening', 'Hair straightening'), ('Facial', 'Facial'), ('Hair Spa', 'Hair Spa'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Makeup', 'Makeup')], max_length=50, unique=True),
        ),
    ]
