# Generated by Django 4.1.7 on 2023-05-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0046_alter_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Time_slot',
            field=models.CharField(choices=[('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('21:00-22:00', '21:00-22:00'), ('13:00-14:00', '13:00-14:00'), ('18:00-19:00', '18:00-19:00'), ('20:00-21:00', '20:00-21:00'), ('10:00-11:00', '10:00-11:00'), ('19:00-20:00', '19:00-20:00')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Waxing', 'Waxing'), ('Bleach', 'Bleach'), ('Nail art', 'Nail art'), ('Hair smoothening', 'Hair smoothening'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Haircuts', 'Haircuts'), ('Threading', 'Threading'), ('Hair Spa', 'Hair Spa'), ('Makeup', 'Makeup'), ('Hair straightening', 'Hair straightening'), ('Hairstyling', 'Hairstyling'), ('Pedicure', 'Pedicure'), ('Manicure', 'Manicure'), ('Facial', 'Facial')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palour.userdetail')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='palour.payment'),
        ),
    ]
