# Generated by Django 4.2 on 2023-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palour", "0047_alter_booking_time_slot_alter_booking_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Time_slot",
            field=models.CharField(
                choices=[
                    ("18:00-19:00", "18:00-19:00"),
                    ("11:00-12:00", "11:00-12:00"),
                    ("13:00-14:00", "13:00-14:00"),
                    ("10:00-11:00", "10:00-11:00"),
                    ("19:00-20:00", "19:00-20:00"),
                    ("12:00-13:00", "12:00-13:00"),
                    ("21:00-22:00", "21:00-22:00"),
                    ("20:00-21:00", "20:00-21:00"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicemaster",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("Waxing", "Waxing"),
                    ("Hair coloring/Highlights", "Hair coloring/Highlights"),
                    ("Bleach", "Bleach"),
                    ("Haircuts", "Haircuts"),
                    ("Nail art", "Nail art"),
                    ("Makeup", "Makeup"),
                    ("Hairstyling", "Hairstyling"),
                    ("Threading", "Threading"),
                    ("Pedicure", "Pedicure"),
                    ("Hair smoothening", "Hair smoothening"),
                    ("Facial", "Facial"),
                    ("Hair Spa", "Hair Spa"),
                    ("Manicure", "Manicure"),
                    ("Hair straightening", "Hair straightening"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
