# Generated by Django 4.1.7 on 2023-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palour', '0048_alter_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Time_slot',
            field=models.CharField(choices=[('20:00-21:00', '20:00-21:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('10:00-11:00', '10:00-11:00'), ('21:00-22:00', '21:00-22:00'), ('19:00-20:00', '19:00-20:00'), ('18:00-19:00', '18:00-19:00')], max_length=50),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='service_name',
            field=models.CharField(choices=[('Hair straightening', 'Hair straightening'), ('Hair smoothening', 'Hair smoothening'), ('Haircuts', 'Haircuts'), ('Makeup', 'Makeup'), ('Bleach', 'Bleach'), ('Threading', 'Threading'), ('Hair Spa', 'Hair Spa'), ('Hair coloring/Highlights', 'Hair coloring/Highlights'), ('Manicure', 'Manicure'), ('Pedicure', 'Pedicure'), ('Hairstyling', 'Hairstyling'), ('Facial', 'Facial'), ('Waxing', 'Waxing'), ('Nail art', 'Nail art')], max_length=50, unique=True),
        ),
    ]
